@startuml FSM

note "When daytime:\n -> D=1, Su=1, Sd=0\n\nWhen nighttime:\n -> D=0,Su=0,Sd=1" as N1

Sleep : sleep 5 min
MotorStop : stop motor
MotorRun : start motor up/down
MotorCheck : day -> upper sensor should be on
MotorCheck : night -> bottom sensor should be on

[*] --> Sensor
Sensor : Store sensor values in state
Sensor : Sanity check sensor values

Sensor --> Sleep : day/night **not** changed
Sleep --> Sensor : Wake up
Sensor --> MotorRun : **changed**

MotorRun --> MotorCheck

MotorCheck --> MotorCheck : sensor **not** end
MotorCheck --> MotorStop : sensor **end**

MotorStop --> Sensor

		
@enduml
